#include <stdio.h>

#include <SFML/Graphics.h>

#include "main_menu.h"
#include "mouse.h"
#include "resources.h"

// Code generated by @ChatGPT

#define WINDOW_WIDTH  1600
#define WINDOW_HEIGHT 900

typedef struct TestResults
{
    unsigned int passed;
    unsigned int failed;

} TestResults;

static void test_check(TestResults* results, sfBool condition, const char* message)
{
    if (condition)
    {
        ++results->passed;
        printf("[PASS] %s\n", message);
        return;
    }

    ++results->failed;
    printf("[FAIL] %s\n", message);
}

static const char* mainMenuAction_toString(MainMenuAction action)
{
    switch (action)
    {
        case mainMenuActionNone:
            return "None";

        case mainMenuActionPlay:
            return "Play";

        case mainMenuActionSettings:
            return "Settings";

        case mainMenuActionCredits:
            return "Credits";

        case mainMenuActionExit:
            return "Exit";

        default:
            return "Unknown";
    }
}

static void test_textureLoading(TestResults* results, const Resources* resources)
{
    printf("\n=== Texture loading ===\n");

    test_check(
        results,
        resources_getTexture(resources, resourceTextureBackground) != NULL,
        "background texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTextureBoard) != NULL,
        "board texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTextureButtons) != NULL,
        "buttons texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTexturePieces) != NULL,
        "pieces texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTextureSideboard) != NULL,
        "sideboard texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTextureTimeBoard) != NULL,
        "time board texture loaded"
    );

    test_check(
        results,
        resources_getTexture(resources, resourceTextureTitleBoard) != NULL,
        "title board texture loaded"
    );
}

static void test_iconLoading(TestResults* results, const Resources* resources)
{
    printf("\n=== Icon loading ===\n");

    test_check(
        results,
        resources_getIcon(resources, resourceIconDraw) != NULL,
        "draw icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconGameLogo) != NULL,
        "game logo icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconResign) != NULL,
        "resign icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconSettingWhite) != NULL,
        "white settings icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconSettings) != NULL,
        "settings icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconSfmlLogo) != NULL,
        "SFML logo icon loaded"
    );

    test_check(
        results,
        resources_getIcon(resources, resourceIconStockfish) != NULL,
        "Stockfish icon loaded"
    );
}

static void test_fontLoading(TestResults* results, const Resources* resources)
{
    printf("\n=== Font loading ===\n");

    test_check(
        results,
        resources_getFont(resources, resourceFontCinzelMedium) != NULL,
        "Cinzel Medium font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontCinzelRegular) != NULL,
        "Cinzel Regular font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontCinzelSemiBold) != NULL,
        "Cinzel SemiBold font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoItalic) != NULL,
        "JetBrains Mono Italic font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoLight) != NULL,
        "JetBrains Mono Light font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoLightItalic) != NULL,
        "JetBrains Mono Light Italic font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoRegular) != NULL,
        "JetBrains Mono Regular font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoSemiBold) != NULL,
        "JetBrains Mono SemiBold font loaded"
    );

    test_check(
        results,
        resources_getFont(resources, resourceFontJetBrainsMonoSemiBoldItalic) != NULL,
        "JetBrains Mono SemiBold Italic font loaded"
    );
}

static void test_resourcesBehaviour(TestResults* results, const Resources* resources)
{
    const sfTexture* buttonsA;
    const sfTexture* buttonsB;

    const sfFont* cinzelA;
    const sfFont* cinzelB;

    printf("\n=== Resources behaviour ===\n");

    buttonsA = resources_getTexture(resources, resourceTextureButtons);
    buttonsB = resources_getTexture(resources, resourceTextureButtons);

    cinzelA = resources_getFont(resources, resourceFontCinzelSemiBold);
    cinzelB = resources_getFont(resources, resourceFontCinzelSemiBold);

    test_check(
        results,
        buttonsA != NULL && buttonsA == buttonsB,
        "texture getter returns stable borrowed pointer"
    );

    test_check(
        results,
        cinzelA != NULL && cinzelA == cinzelB,
        "font getter returns stable borrowed pointer"
    );
}

static void test_mainMenuCreation(TestResults* results, mainMenu* menu)
{
    printf("\n=== Main menu creation ===\n");

    test_check(
        results,
        menu != NULL,
        "main menu object created"
    );

    if (menu == NULL)
        return;

    test_check(
        results,
        mainMenu_isActive(menu) == sfTrue,
        "main menu starts active"
    );

    test_check(
        results,
        mainMenu_getAction(menu) == mainMenuActionNone,
        "main menu starts with no pending action"
    );

    mainMenu_setActive(menu, sfFalse);

    test_check(
        results,
        mainMenu_isActive(menu) == sfFalse,
        "main menu can be deactivated"
    );

    mainMenu_setActive(menu, sfTrue);

    test_check(
        results,
        mainMenu_isActive(menu) == sfTrue,
        "main menu can be reactivated"
    );
}

static void print_testSummary(const TestResults* results)
{
    printf("\n=== Test summary ===\n");
    printf("Passed: %u\n", results->passed);
    printf("Failed: %u\n", results->failed);

    if (results->failed == 0)
        printf("Result: basic startup tests passed.\n");
    else
        printf("Result: fix the failed checks before continuing.\n");
}

int main(void)
{
    TestResults results = {0, 0};

    Resources* resources;
    mainMenu* menu;
    Mouse* mouse;

    sfRenderWindow* window;
    sfRectangleShape* background;

    sfEvent event;

    resources = resources_create();

    test_check(
        &results,
        resources != NULL,
        "resources object created"
    );

    if (resources == NULL)
    {
        print_testSummary(&results);
        return 1;
    }

    test_textureLoading(&results, resources);
    test_iconLoading(&results, resources);
    test_fontLoading(&results, resources);
    test_resourcesBehaviour(&results, resources);

    sfContextSettings settings = {0};

    settings.antialiasingLevel = 8;

    window = sfRenderWindow_create(
    (sfVideoMode){WINDOW_WIDTH, WINDOW_HEIGHT, 32},
    "Chess: Main Menu Test",
    sfClose,
    &settings
);

    test_check(
        &results,
        window != NULL,
        "render window created"
    );

    if (window == NULL)
    {
        resources_destroy(resources);
        print_testSummary(&results);
        return 1;
    }

    sfRenderWindow_setFramerateLimit(window, 60);

    background = sfRectangleShape_create();

    test_check(
        &results,
        background != NULL,
        "background shape created"
    );

    if (background != NULL)
    {
        sfRectangleShape_setSize(
            background,
            (sfVector2f){WINDOW_WIDTH, WINDOW_HEIGHT}
        );

        sfRectangleShape_setTexture(
            background,
            resources_getTexture(resources, resourceTextureBackground),
            sfTrue
        );
    }

    menu = mainMenu_create(
        (sfVector2i){0, 0},
        (sfVector2i){WINDOW_WIDTH, WINDOW_HEIGHT},
        resources
    );

    test_mainMenuCreation(&results, menu);

    if (menu == NULL)
    {
        if (background != NULL)
            sfRectangleShape_destroy(background);

        sfRenderWindow_destroy(window);
        resources_destroy(resources);

        print_testSummary(&results);
        return 1;
    }

    mouse = mouse_create(sfMouseLeft);

    test_check(
        &results,
        mouse != NULL,
        "mouse object created"
    );

    if (mouse == NULL)
    {
        mainMenu_destroy(menu);

        if (background != NULL)
            sfRectangleShape_destroy(background);

        sfRenderWindow_destroy(window);
        resources_destroy(resources);

        print_testSummary(&results);
        return 1;
    }

    print_testSummary(&results);

    printf("\n=== Manual visual/action test ===\n");
    printf("Expected visual result:\n");
    printf("- background texture is visible\n");
    printf("- titlebar is visible\n");
    printf("- Play, Settings, Credits, and Exit buttons are visible\n");
    printf("- button hover/press texture changes work\n");
    printf("\nExpected action result:\n");
    printf("- clicking Exit prints the Exit action and closes the window\n");
    printf("- pressing Escape also closes the window\n\n");

    while (sfRenderWindow_isOpen(window))
    {
        while (sfRenderWindow_pollEvent(window, &event))
        {
            if (event.type == sfEvtClosed)
                sfRenderWindow_close(window);

            if (event.type == sfEvtKeyReleased && event.key.code == sfKeyEscape)
                sfRenderWindow_close(window);
        }

        mouse_update(mouse, window);
        mainMenu_updateMouse(menu, mouse);

        {
            MainMenuAction action;

            action = mainMenu_consumeAction(menu);

            if (action != mainMenuActionNone)
            {
                printf("[MENU ACTION] %s\n", mainMenuAction_toString(action));

                if (action == mainMenuActionExit)
                    sfRenderWindow_close(window);
            }
        }

        sfRenderWindow_clear(window, sfBlack);

        if (background != NULL)
            sfRenderWindow_drawRectangleShape(window, background, NULL);

        mainMenu_draw(window, menu);

        sfRenderWindow_display(window);
    }

    mouse_destroy(mouse);
    mainMenu_destroy(menu);

    if (background != NULL)
        sfRectangleShape_destroy(background);

    sfRenderWindow_destroy(window);
    resources_destroy(resources);

    return results.failed == 0 ? 0 : 1;
}

// End of code segment